/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: nsis scripting language templating */
import path from 'node:path';
import fs from 'node:fs';
import { MakerBase } from '@electron-forge/maker-base';
import type { MakerOptions } from '@electron-forge/maker-base';
import { promisify } from 'node:util';
import { tmpdir } from 'node:os';
import { INSTALLER_ART_DIR, INSTALLER_ART_FILES, writeInstallerArt } from './generate-installer-art.mjs';
function resolveIcon(iconPath: string | undefined): string | undefined {
	if (!iconPath) return undefined;
	const absolute = path.isAbsolute(iconPath) ? iconPath : path.resolve(process.cwd(), iconPath);
	const withIcoExt = path.extname(absolute).toLowerCase() === '.ico' ? absolute : `${absolute.replace(/\.[^/.]+$/, '')}.ico`;
	try {
		fs.accessSync(withIcoExt);
		return withIcoExt;
	} catch {
		return undefined;
	}
}
function resolveInstallerArt():
	| {
			header: string;
			side: string;
	  }
	| undefined {
	const header = path.join(INSTALLER_ART_DIR, INSTALLER_ART_FILES.header);
	const side = path.join(INSTALLER_ART_DIR, INSTALLER_ART_FILES.side);
	if (fs.existsSync(header) && fs.existsSync(side)) return { header, side };
	try {
		writeInstallerArt();
		return { header, side };
	} catch (error) {
		console.warn(`Building the installer without branding bitmaps: ${(error as Error).message}`);
		return undefined;
	}
}
function nsisText(value: string): string {
	return value
		.replace(/[\r\n]+/g, ' ')
		.replace(/\$/g, '$$$$')
		.replace(/"/g, '$\\"')
		.trim();
}
export interface InstallerScriptOptions {
	appDisplayName: string;
	executableName: string;
	version: string;
	windowsVersion: string;
	publisher: string;
	copyright: string;
	description: string;
	sourceDir: string;
	outFile: string;
	uninstallKey: string;
	iconPath?: string;
	licensePath?: string;
	headerBitmapPath?: string;
	sideBitmapPath?: string;
	homepageUrl?: string;
	supportUrl?: string;
	updatesUrl?: string;
	protocolSchemes?: string[];
}
export function buildInstallerScript(options: InstallerScriptOptions): string {
	const {
		appDisplayName,
		executableName,
		version,
		windowsVersion,
		publisher,
		copyright,
		description,
		sourceDir,
		outFile,
		uninstallKey,
		iconPath,
		licensePath,
		headerBitmapPath,
		sideBitmapPath,
		homepageUrl,
		supportUrl,
		updatesUrl,
		protocolSchemes = []
	} = options;
	const versionParts = version.split(/[.\-+]/);
	const versionMajor = Number.parseInt(versionParts[0] ?? '0', 10) || 0;
	const versionMinor = Number.parseInt(versionParts[1] ?? '0', 10) || 0;
	const lines: string[] = [];
	const push = (...text: string[]) => lines.push(...text);
	push(
		`; ${appDisplayName} ${version} Windows installer.`,
		'; Generated by MakerNSIS.ts during "pnpm run make" - edit the maker, not this file.',
		'',
		'Unicode true',
		'SetCompressor /SOLID lzma',
		'ManifestDPIAware true',
		'SetOverwrite on',
		'',
		'!include "MUI2.nsh"',
		'!include "FileFunc.nsh"',
		'!include "LogicLib.nsh"',
		'!include "Sections.nsh"',
		'!insertmacro GetSize',
		'!insertmacro GetTime',
		'!insertmacro GetParameters',
		'!insertmacro GetOptions',
		'',
		`!define WOK_NAME "${nsisText(appDisplayName)}"`,
		`!define WOK_VERSION "${nsisText(version)}"`,
		`!define WOK_PUBLISHER "${nsisText(publisher)}"`,
		`!define WOK_EXE "${nsisText(executableName)}"`,
		`!define WOK_UNINSTALL_KEY "${nsisText(uninstallKey)}"`,
		'',
		'Name "${WOK_NAME}"',
		'Caption "${WOK_NAME} ${WOK_VERSION} Setup"',
		'UninstallCaption "${WOK_NAME} ${WOK_VERSION} Uninstall"',
		`OutFile "${nsisText(outFile)}"`,
		'BrandingText "${WOK_NAME} ${WOK_VERSION}"',
		'',
		`VIProductVersion "${windowsVersion}"`,
		`VIFileVersion "${windowsVersion}"`,
		'VIAddVersionKey "ProductName" "${WOK_NAME}"',
		'VIAddVersionKey "CompanyName" "${WOK_PUBLISHER}"',
		`VIAddVersionKey "FileDescription" "${nsisText(`${appDisplayName} Setup`)}"`,
		`VIAddVersionKey "FileVersion" "${nsisText(version)}"`,
		`VIAddVersionKey "ProductVersion" "${nsisText(version)}"`,
		`VIAddVersionKey "LegalCopyright" "${nsisText(copyright)}"`,
		`VIAddVersionKey "OriginalFilename" "${nsisText(path.win32.basename(outFile))}"`,
		'',
		'; Per-user install: no elevation prompt, no shared state, nothing outside HKCU.',
		'RequestExecutionLevel user',
		'InstallDir "$LOCALAPPDATA\\${WOK_NAME}"',
		'InstallDirRegKey HKCU "${WOK_UNINSTALL_KEY}" "InstallLocation"',
		'ShowInstDetails show',
		'ShowUnInstDetails show',
		''
	);
	push(';--------------------------------', '; Interface', '', '!define MUI_ABORTWARNING', '!define MUI_UNABORTWARNING');
	if (iconPath) {
		push(`!define MUI_ICON "${nsisText(iconPath)}"`, `!define MUI_UNICON "${nsisText(iconPath)}"`);
	}
	if (headerBitmapPath && sideBitmapPath) {
		push(
			'',
			'; Branding bitmaps are generated from assets/*.svg by scripts/generate-installer-art.mjs.',
			'!define MUI_HEADERIMAGE',
			`!define MUI_HEADERIMAGE_BITMAP "${nsisText(headerBitmapPath)}"`,
			`!define MUI_HEADERIMAGE_UNBITMAP "${nsisText(headerBitmapPath)}"`,
			`!define MUI_WELCOMEFINISHPAGE_BITMAP "${nsisText(sideBitmapPath)}"`,
			`!define MUI_UNWELCOMEFINISHPAGE_BITMAP "${nsisText(sideBitmapPath)}"`
		);
	}
	push(
		'',
		'; Dark log window with the brand accent, matching the app itself.',
		'!define MUI_INSTFILESPAGE_COLORS "FBC02D 101014"',
		'!define MUI_COMPONENTSPAGE_SMALLDESC',
		'; Leave the progress log on screen so the install steps can be read.',
		'!define MUI_FINISHPAGE_NOAUTOCLOSE',
		'!define MUI_UNFINISHPAGE_NOAUTOCLOSE',
		''
	);
	push(
		';--------------------------------',
		'; Installer pages',
		'',
		'!define MUI_WELCOMEPAGE_TITLE "Install ${WOK_NAME}"',
		'!define MUI_WELCOMEPAGE_TITLE_3LINES',
		'!define MUI_WELCOMEPAGE_TEXT "Setup installs ${WOK_NAME} ${WOK_VERSION} on this computer.$\\r$\\n$\\r$\\n' +
			`${nsisText(description)}$\\r$\\n$\\r$\\n` +
			'It installs for the current user only, so Windows will not ask for administrator rights, and it can be removed again from Settings > Apps.$\\r$\\n$\\r$\\n' +
			'Close ${WOK_NAME} before continuing. $_CLICK"',
		'!insertmacro MUI_PAGE_WELCOME',
		''
	);
	if (licensePath) {
		push(
			'!define MUI_LICENSEPAGE_BUTTON "Next >"',
			'!define MUI_LICENSEPAGE_TEXT_TOP "${WOK_NAME} is free software under the GNU General Public License version 3."',
			'!define MUI_LICENSEPAGE_TEXT_BOTTOM "You do not have to accept anything to install ${WOK_NAME}. ' + 'This page is here so you know your rights to use, study, share and modify it. Click Next to continue."',
			`!insertmacro MUI_PAGE_LICENSE "${nsisText(licensePath)}"`,
			''
		);
	}
	push(
		'!insertmacro MUI_PAGE_COMPONENTS',
		'',
		'!define MUI_DIRECTORYPAGE_TEXT_TOP "Choose where to install ${WOK_NAME}. ' + 'The default is a per-user folder, which keeps the install out of Program Files and avoids an administrator prompt."',
		'!insertmacro MUI_PAGE_DIRECTORY',
		'',
		'!insertmacro MUI_PAGE_INSTFILES',
		'',
		'!define MUI_FINISHPAGE_TITLE "${WOK_NAME} is installed"',
		'!define MUI_FINISHPAGE_TITLE_3LINES',
		'!define MUI_FINISHPAGE_TEXT "${WOK_NAME} ${WOK_VERSION} was installed in $INSTDIR.$\\r$\\n$\\r$\\n' +
			'The first launch checks your hardware before it picks graphics settings, so it can take longer than later launches."',
		'!define MUI_FINISHPAGE_RUN "$INSTDIR\\${WOK_EXE}"',
		'!define MUI_FINISHPAGE_RUN_TEXT "Launch ${WOK_NAME}"'
	);
	if (homepageUrl) {
		push(`!define MUI_FINISHPAGE_LINK "${nsisText(homepageUrl.replace(/^https?:\/\//, ''))}"`, `!define MUI_FINISHPAGE_LINK_LOCATION "${nsisText(homepageUrl)}"`);
	}
	push('!insertmacro MUI_PAGE_FINISH', '');
	push(
		';--------------------------------',
		'; Uninstaller pages',
		'',
		'; MUI2 reuses the welcome and finish defines for the uninstaller, so each one',
		'; is released before it is set again.',
		'!ifdef MUI_WELCOMEPAGE_TITLE',
		'  !undef MUI_WELCOMEPAGE_TITLE',
		'!endif',
		'!ifdef MUI_WELCOMEPAGE_TEXT',
		'  !undef MUI_WELCOMEPAGE_TEXT',
		'!endif',
		'!define MUI_WELCOMEPAGE_TITLE "Remove ${WOK_NAME}"',
		'!define MUI_WELCOMEPAGE_TEXT "This removes ${WOK_NAME} ${WOK_VERSION} and its shortcuts from this computer.$\\r$\\n$\\r$\\n' +
			'Your settings, calibration results and profile stay in $APPDATA\\${WOK_NAME}, so reinstalling picks up where you left off. ' +
			'Delete that folder yourself if you want a clean slate.$\\r$\\n$\\r$\\n' +
			'Close ${WOK_NAME} before continuing. $_CLICK"',
		'!insertmacro MUI_UNPAGE_WELCOME',
		'',
		'!define MUI_UNCONFIRMPAGE_TEXT_TOP "${WOK_NAME} will be removed from the folder below, along with its Start Menu and desktop shortcuts and its Windows registration."',
		'!insertmacro MUI_UNPAGE_CONFIRM',
		'',
		'!insertmacro MUI_UNPAGE_INSTFILES',
		'',
		'; The uninstaller must never inherit the installer finish page controls: a',
		'; leftover run checkbox would point at an executable that no longer exists.',
		'!ifdef MUI_FINISHPAGE_RUN',
		'  !undef MUI_FINISHPAGE_RUN',
		'!endif',
		'!ifdef MUI_FINISHPAGE_RUN_TEXT',
		'  !undef MUI_FINISHPAGE_RUN_TEXT',
		'!endif',
		'!ifdef MUI_FINISHPAGE_LINK',
		'  !undef MUI_FINISHPAGE_LINK',
		'!endif',
		'!ifdef MUI_FINISHPAGE_LINK_LOCATION',
		'  !undef MUI_FINISHPAGE_LINK_LOCATION',
		'!endif',
		'!ifdef MUI_FINISHPAGE_TITLE',
		'  !undef MUI_FINISHPAGE_TITLE',
		'!endif',
		'!ifdef MUI_FINISHPAGE_TEXT',
		'  !undef MUI_FINISHPAGE_TEXT',
		'!endif',
		'!ifdef MUI_FINISHPAGE_TITLE_3LINES',
		'  !undef MUI_FINISHPAGE_TITLE_3LINES',
		'!endif',
		'!define MUI_FINISHPAGE_TITLE "${WOK_NAME} was removed"',
		'!define MUI_FINISHPAGE_TITLE_3LINES',
		'!define MUI_FINISHPAGE_TEXT "${WOK_NAME} is no longer installed on this computer.$\\r$\\n$\\r$\\n' + 'Your settings in $APPDATA\\${WOK_NAME} were left in place."',
		'!insertmacro MUI_UNPAGE_FINISH',
		'',
		'!insertmacro MUI_LANGUAGE "English"',
		''
	);
	push(
		';--------------------------------',
		'; Sections',
		'',
		'Var PreviousVersion',
		'',
		'Section "!${WOK_NAME}" SecCore',
		'  SectionIn RO',
		'  SetShellVarContext current',
		'  SetDetailsPrint both',
		'',
		'  DetailPrint "Checking whether ${WOK_NAME} is running..."',
		'  Call EnsureAppClosed',
		'',
		'  ${If} $PreviousVersion != ""',
		'    DetailPrint "Replacing ${WOK_NAME} $PreviousVersion..."',
		'    ; Drop the previous Electron payload so stale locales and resources cannot survive an upgrade.',
		'    RMDir /r "$INSTDIR\\resources"',
		'    RMDir /r "$INSTDIR\\locales"',
		'  ${EndIf}',
		'',
		'  DetailPrint "Copying ${WOK_NAME} to $INSTDIR..."',
		'  SetOutPath "$INSTDIR"',
		`  File /r "${nsisText(sourceDir)}\\*.*"`,
		'',
		'  DetailPrint "Writing the uninstaller..."',
		'  WriteUninstaller "$INSTDIR\\Uninstall.exe"',
		'',
		'  DetailPrint "Registering ${WOK_NAME} with Windows..."',
		'  WriteRegStr HKCU "${WOK_UNINSTALL_KEY}" "DisplayName" "${WOK_NAME}"',
		'  WriteRegStr HKCU "${WOK_UNINSTALL_KEY}" "DisplayVersion" "${WOK_VERSION}"',
		'  WriteRegStr HKCU "${WOK_UNINSTALL_KEY}" "Publisher" "${WOK_PUBLISHER}"',
		`  WriteRegStr HKCU "\${WOK_UNINSTALL_KEY}" "Comments" "${nsisText(description)}"`,
		'  WriteRegStr HKCU "${WOK_UNINSTALL_KEY}" "InstallLocation" "$INSTDIR"',
		'  WriteRegStr HKCU "${WOK_UNINSTALL_KEY}" "UninstallString" \'"$INSTDIR\\Uninstall.exe"\'',
		'  WriteRegStr HKCU "${WOK_UNINSTALL_KEY}" "QuietUninstallString" \'"$INSTDIR\\Uninstall.exe" /S\'',
		'  WriteRegStr HKCU "${WOK_UNINSTALL_KEY}" "DisplayIcon" \'"$INSTDIR\\${WOK_EXE}",0\'',
		`  WriteRegDWORD HKCU "\${WOK_UNINSTALL_KEY}" "VersionMajor" ${versionMajor}`,
		`  WriteRegDWORD HKCU "\${WOK_UNINSTALL_KEY}" "VersionMinor" ${versionMinor}`
	);
	if (homepageUrl) push(`  WriteRegStr HKCU "\${WOK_UNINSTALL_KEY}" "URLInfoAbout" "${nsisText(homepageUrl)}"`);
	if (supportUrl) push(`  WriteRegStr HKCU "\${WOK_UNINSTALL_KEY}" "HelpLink" "${nsisText(supportUrl)}"`);
	if (updatesUrl) push(`  WriteRegStr HKCU "\${WOK_UNINSTALL_KEY}" "URLUpdateInfo" "${nsisText(updatesUrl)}"`);
	push(
		'  WriteRegDWORD HKCU "${WOK_UNINSTALL_KEY}" "NoModify" 1',
		'  WriteRegDWORD HKCU "${WOK_UNINSTALL_KEY}" "NoRepair" 1',
		'  ; Settings > Apps sorts and filters on the install date.',
		'  ${GetTime} "" "L" $0 $1 $2 $3 $4 $5 $6',
		'  WriteRegStr HKCU "${WOK_UNINSTALL_KEY}" "InstallDate" "$2$1$0"',
		'',
		'  ; App Paths and Applications metadata improve Start search and Run discovery.',
		'  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\${WOK_EXE}" "" "$INSTDIR\\${WOK_EXE}"',
		'  WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\${WOK_EXE}" "Path" "$INSTDIR"',
		'  WriteRegStr HKCU "Software\\Classes\\Applications\\${WOK_EXE}" "FriendlyAppName" "${WOK_NAME}"',
		'  WriteRegStr HKCU "Software\\Classes\\Applications\\${WOK_EXE}" "ApplicationCompany" "${WOK_PUBLISHER}"',
		'  WriteRegStr HKCU "Software\\Classes\\Applications\\${WOK_EXE}\\shell\\open\\command" "" \'"$INSTDIR\\${WOK_EXE}" "%1"\'',
		'',
		'  DetailPrint "Recording the installed size..."',
		'  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2',
		'  WriteRegDWORD HKCU "${WOK_UNINSTALL_KEY}" "EstimatedSize" "$0"',
		'  DetailPrint "${WOK_NAME} ${WOK_VERSION} installed."',
		'SectionEnd',
		'',
		'Section "Start Menu shortcut" SecStartMenu',
		'  SetShellVarContext current',
		'  SetDetailsPrint both',
		'  DetailPrint "Creating the Start Menu shortcut..."',
		'  ; Keep the app at the Start Menu root so Windows Search indexes it immediately.',
		'  Delete "$SMPROGRAMS\\${WOK_NAME}\\${WOK_NAME}.lnk"',
		'  Delete "$SMPROGRAMS\\${WOK_NAME}\\Uninstall ${WOK_NAME}.lnk"',
		'  RMDir "$SMPROGRAMS\\${WOK_NAME}"',
		'  CreateShortCut "$SMPROGRAMS\\${WOK_NAME}.lnk" "$INSTDIR\\${WOK_EXE}" "" "$INSTDIR\\${WOK_EXE}" 0 SW_SHOWNORMAL "" "${WOK_NAME}"',
		'SectionEnd',
		'',
		'Section "Desktop shortcut" SecDesktop',
		'  SetShellVarContext current',
		'  SetDetailsPrint both',
		'  DetailPrint "Creating the desktop shortcut..."',
		'  CreateShortCut "$DESKTOP\\${WOK_NAME}.lnk" "$INSTDIR\\${WOK_EXE}" "" "$INSTDIR\\${WOK_EXE}" 0 SW_SHOWNORMAL "" "${WOK_NAME}"',
		'SectionEnd',
		'',
		'!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN',
		'  !insertmacro MUI_DESCRIPTION_TEXT ${SecCore} "${WOK_NAME} ${WOK_VERSION} and its uninstaller. Required."',
		'  !insertmacro MUI_DESCRIPTION_TEXT ${SecStartMenu} "Add ${WOK_NAME} to the Start Menu so Windows Search can find it."',
		'  !insertmacro MUI_DESCRIPTION_TEXT ${SecDesktop} "Put a ${WOK_NAME} shortcut on the desktop."',
		'!insertmacro MUI_FUNCTION_DESCRIPTION_END',
		''
	);
	push(
		';--------------------------------',
		'; Functions',
		'',
		'Function .onInit',
		'  ; Silent installs (/S) keep every default component. /NODESKTOP and /NOSTARTMENU',
		'  ; drop the optional shortcuts, /D=<dir> still chooses the target folder.',
		'  ${GetParameters} $R0',
		'  ClearErrors',
		'  ${GetOptions} $R0 "/NODESKTOP" $R1',
		'  ${IfNot} ${Errors}',
		'    !insertmacro UnselectSection ${SecDesktop}',
		'  ${EndIf}',
		'  ClearErrors',
		'  ${GetOptions} $R0 "/NOSTARTMENU" $R1',
		'  ${IfNot} ${Errors}',
		'    !insertmacro UnselectSection ${SecStartMenu}',
		'  ${EndIf}',
		'  ClearErrors',
		'  ReadRegStr $PreviousVersion HKCU "${WOK_UNINSTALL_KEY}" "DisplayVersion"',
		'  ClearErrors',
		'FunctionEnd',
		'',
		'; A running Electron app holds its own image file open without write sharing, so',
		'; opening the exe for append is a non-destructive "is it running" probe.',
		'Function EnsureAppClosed',
		'  IfFileExists "$INSTDIR\\${WOK_EXE}" 0 done',
		'  retry:',
		'    ClearErrors',
		'    FileOpen $R9 "$INSTDIR\\${WOK_EXE}" a',
		'    ${IfNot} ${Errors}',
		'      FileClose $R9',
		'      Goto done',
		'    ${EndIf}',
		'    MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION "${WOK_NAME} is still running. Close it, then click Retry." /SD IDCANCEL IDRETRY retry',
		'    Abort "${WOK_NAME} is running. Close it and start the installer again."',
		'  done:',
		'  ClearErrors',
		'FunctionEnd',
		'',
		'Function un.EnsureAppClosed',
		'  IfFileExists "$INSTDIR\\${WOK_EXE}" 0 done',
		'  retry:',
		'    ClearErrors',
		'    FileOpen $R9 "$INSTDIR\\${WOK_EXE}" a',
		'    ${IfNot} ${Errors}',
		'      FileClose $R9',
		'      Goto done',
		'    ${EndIf}',
		'    MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION "${WOK_NAME} is still running. Close it, then click Retry." /SD IDCANCEL IDRETRY retry',
		'    Abort "${WOK_NAME} is running. Close it and start the uninstaller again."',
		'  done:',
		'  ClearErrors',
		'FunctionEnd',
		''
	);
	if (protocolSchemes.length > 0) {
		push(
			'; The app registers its URL schemes itself on first run. Only remove a handler',
			'; that still points at this installation.',
			'!macro RemoveProtocolHandler SCHEME',
			'  ReadRegStr $R0 HKCU "Software\\Classes\\${SCHEME}\\shell\\open\\command" ""',
			'  StrCpy $R1 \'"$INSTDIR\\${WOK_EXE}"\'',
			'  StrLen $R2 $R1',
			'  StrCpy $R3 $R0 $R2',
			'  ${If} $R3 == $R1',
			'    DetailPrint "Removing the ${SCHEME}: link handler..."',
			'    DeleteRegKey HKCU "Software\\Classes\\${SCHEME}"',
			'  ${EndIf}',
			'!macroend',
			''
		);
	}
	push(
		';--------------------------------',
		'; Uninstaller',
		'',
		'Section "Uninstall"',
		'  SetShellVarContext current',
		'  SetDetailsPrint both',
		'',
		'  DetailPrint "Checking whether ${WOK_NAME} is running..."',
		'  Call un.EnsureAppClosed',
		'',
		'  DetailPrint "Removing shortcuts..."',
		'  Delete "$SMPROGRAMS\\${WOK_NAME}.lnk"',
		'  Delete "$SMPROGRAMS\\${WOK_NAME}\\${WOK_NAME}.lnk"',
		'  Delete "$SMPROGRAMS\\${WOK_NAME}\\Uninstall ${WOK_NAME}.lnk"',
		'  RMDir "$SMPROGRAMS\\${WOK_NAME}"',
		'  Delete "$DESKTOP\\${WOK_NAME}.lnk"',
		'',
		'  DetailPrint "Removing the Windows registration..."',
		'  DeleteRegKey HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\${WOK_EXE}"',
		'  DeleteRegKey HKCU "Software\\Classes\\Applications\\${WOK_EXE}"'
	);
	for (const scheme of protocolSchemes) {
		push(`  !insertmacro RemoveProtocolHandler "${nsisText(scheme)}"`);
	}
	push(
		'  DeleteRegKey HKCU "${WOK_UNINSTALL_KEY}"',
		'',
		'  DetailPrint "Removing application files from $INSTDIR..."',
		'  ${If} ${FileExists} "$INSTDIR\\${WOK_EXE}"',
		'    RMDir /r "$INSTDIR"',
		'  ${Else}',
		'    ; Not our install directory any more: only take back what we know we wrote.',
		'    Delete "$INSTDIR\\Uninstall.exe"',
		'    RMDir "$INSTDIR"',
		'  ${EndIf}',
		'',
		'  DetailPrint "Settings in $APPDATA\\${WOK_NAME} were left in place."',
		'  DetailPrint "${WOK_NAME} was removed."',
		'SectionEnd',
		''
	);
	return `${lines.join('\n')}\n`;
}
export class MakerNSIS extends MakerBase<{}> {
	name = 'nsis';
	defaultPlatforms: MakerOptions['targetPlatform'][] = ['win32'];
	requiredExternalBinaries = ['makensis'];
	isSupportedOnCurrentPlatform() {
		return true;
	}
	async make(opts: MakerOptions) {
		const { dir, makeDir, appName, packageJSON, targetArch, forgeConfig } = opts;
		const packagerConfig = forgeConfig?.packagerConfig ?? {};
		const win32metadata = packagerConfig.win32metadata ?? {};
		const appDisplayName = packagerConfig.name || appName;
		const version = packageJSON.version || '0.0.0';
		const rawAuthor = packageJSON.author as unknown;
		const authorName =
			typeof rawAuthor === 'object' && rawAuthor !== null && 'name' in rawAuthor
				? (
						rawAuthor as {
							name?: string;
						}
					).name
				: (rawAuthor as string | undefined);
		const publisher = win32metadata.CompanyName || authorName || appDisplayName;
		const copyright = packagerConfig.appCopyright || `Copyright © ${new Date().getFullYear()} ${publisher}`;
		const outDir = path.resolve(makeDir, 'nsis', targetArch);
		await this.ensureDirectory(outDir);
		const iconPath = resolveIcon(Array.isArray(packagerConfig.icon) ? packagerConfig.icon?.[0] : packagerConfig.icon);
		const outFile = path.resolve(outDir, `${appDisplayName}-${version}-${targetArch}-setup.exe`);
		const temporaryDirectory = fs.mkdtempSync(path.join(tmpdir(), 'nsis-'));
		const nsiPath = path.resolve(temporaryDirectory, 'installer.nsi');
		const installerArt = resolveInstallerArt();
		const protocolSchemes = (packagerConfig.protocols ?? []).flatMap((protocol) => protocol.schemes ?? []);
		const bugsUrl =
			typeof packageJSON.bugs === 'object' && packageJSON.bugs !== null
				? (
						packageJSON.bugs as {
							url?: string;
						}
					).url
				: (packageJSON.bugs as string | undefined);
		const licenseSource = path.join(import.meta.dirname, 'LICENSE');
		let licensePath: string | undefined;
		if (fs.existsSync(licenseSource)) {
			licensePath = path.resolve(temporaryDirectory, 'license.txt');
			const licenseText = fs.readFileSync(licenseSource, 'utf-8').replace(/\r?\n/g, '\r\n');
			const isAscii = Buffer.byteLength(licenseText, 'utf-8') === licenseText.length;
			fs.writeFileSync(licensePath, `${isAscii ? '' : '\uFEFF'}${licenseText}`, 'utf-8');
		}
		const script = buildInstallerScript({
			appDisplayName,
			executableName: `${packagerConfig.executableName || appName}.exe`,
			version,
			windowsVersion: this.normalizeWindowsVersion(version),
			publisher,
			copyright,
			description: win32metadata.FileDescription || packageJSON.description || '',
			sourceDir: dir,
			outFile,
			uninstallKey: `Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${appDisplayName}`,
			iconPath,
			licensePath,
			headerBitmapPath: installerArt?.header,
			sideBitmapPath: installerArt?.side,
			homepageUrl: packageJSON.homepage,
			supportUrl: bugsUrl,
			updatesUrl: packageJSON.repository?.url?.replace(/^git\+/, '').replace(/\.git$/, ''),
			protocolSchemes
		});
		try {
			fs.writeFileSync(nsiPath, `\uFEFF${script}`, 'utf-8');
			const execFile = promisify((await import('node:child_process')).execFile);
			try {
				await execFile('makensis', ['-NOCD', '-V2', '-WX', nsiPath]);
			} catch (error) {
				const compilerError = error as Error & {
					stderr?: string;
					stdout?: string;
				};
				if (compilerError.stdout) console.error(compilerError.stdout);
				if (compilerError.stderr) console.error(compilerError.stderr);
				throw error;
			}
			return [outFile];
		} finally {
			fs.rmSync(temporaryDirectory, { recursive: true, force: true });
		}
	}
}
