export type OzonePlatform = 'wayland' | 'x11';
export type OzoneDecisionSource = 'not-linux' | 'override' | 'session' | 'fallback';
export interface OzoneDecision {
	platform: OzonePlatform | null;
	source: OzoneDecisionSource;
	signal?: string;
	reason: string;
	warning?: string;
}
export const OZONE_OVERRIDE_ENV_VAR = 'WOK_OZONE_PLATFORM';
export interface WaylandSessionSignal {
	variable: string;
	equals?: string;
	description: string;
}
export const WAYLAND_SESSION_SIGNALS: readonly WaylandSessionSignal[] = [
	{ description: 'a Wayland compositor socket is exported', variable: 'WAYLAND_DISPLAY' },
	{ description: 'the session declares itself as Wayland', equals: 'wayland', variable: 'XDG_SESSION_TYPE' }
];
const OVERRIDE_VALUES = new Set(['auto', 'wayland', 'x11']);
function matchesSignal(signal: WaylandSessionSignal, value: string | undefined): boolean {
	if (value === undefined || value === '') return false;
	return signal.equals === undefined ? true : value === signal.equals;
}
export function detectWaylandSessionSignal(env: Record<string, string | undefined>): WaylandSessionSignal | undefined {
	return WAYLAND_SESSION_SIGNALS.find((signal) => matchesSignal(signal, env[signal.variable]));
}
export function resolveOzonePlatform(env: Record<string, string | undefined>, platform: NodeJS.Platform = process.platform): OzoneDecision {
	if (platform !== 'linux') {
		return { platform: null, reason: 'not Linux; the ozone platform switch does not apply', source: 'not-linux' };
	}
	const rawOverride = env[OZONE_OVERRIDE_ENV_VAR];
	let warning: string | undefined;
	if (rawOverride !== undefined && rawOverride !== '') {
		if (OVERRIDE_VALUES.has(rawOverride)) {
			if (rawOverride === 'auto') {
				return {
					platform: null,
					reason: `${OZONE_OVERRIDE_ENV_VAR}=auto; deferring to Electron's own session detection`,
					source: 'override'
				};
			}
			return {
				platform: rawOverride as OzonePlatform,
				reason: `${OZONE_OVERRIDE_ENV_VAR}=${rawOverride}`,
				signal: OZONE_OVERRIDE_ENV_VAR,
				source: 'override'
			};
		}
		warning = `Ignoring ${OZONE_OVERRIDE_ENV_VAR}=${rawOverride}; expected wayland, x11 or auto.`;
	}
	const waylandSignal = detectWaylandSessionSignal(env);
	if (waylandSignal) {
		return {
			platform: 'wayland',
			reason: `${waylandSignal.variable} says ${waylandSignal.description}`,
			signal: waylandSignal.variable,
			source: 'session',
			warning
		};
	}
	return {
		platform: 'x11',
		reason: 'no Wayland session detected; using X11 (XWayland inside a Wayland session)',
		source: 'fallback',
		warning
	};
}
export function ozoneSwitchArguments(decision: OzoneDecision): string[] {
	return decision.platform === null ? [] : [`--ozone-platform=${decision.platform}`];
}
export function linuxLauncherArguments(env: Record<string, string | undefined>, platform: NodeJS.Platform = process.platform): string[] {
	return ozoneSwitchArguments(resolveOzonePlatform(env, platform));
}
export function describeLinuxDisplaySession(platform: NodeJS.Platform, argv: readonly string[], env: Record<string, string | undefined>): string | null {
	if (platform !== 'linux') return null;
	const decision = resolveOzonePlatform(env, platform);
	let applied: string | undefined;
	for (const argument of argv) {
		if (argument.startsWith('--ozone-platform=')) applied = argument.slice('--ozone-platform='.length);
	}
	if (applied === undefined) {
		return `Display server: chosen by Electron, no --ozone-platform was passed (detected: ${decision.reason})`;
	}
	const waylandSignal = detectWaylandSessionSignal(env);
	if (applied === 'x11' && waylandSignal) {
		return `Display server: x11 through XWayland, but ${waylandSignal.variable} says ${waylandSignal.description}.` + ` Unset or change ${OZONE_OVERRIDE_ENV_VAR} to run natively on Wayland.`;
	}
	return `Display server: ${applied} (${decision.reason})`;
}
const SAFE_EXECUTABLE_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]*$/u;
function renderSignalCondition(signal: WaylandSessionSignal): string {
	return signal.equals === undefined ? `[ -n "$${signal.variable}" ]` : `[ "$${signal.variable}" = "${signal.equals}" ]`;
}
export function renderLinuxLauncherScript(executableName: string): string {
	if (!SAFE_EXECUTABLE_NAME.test(executableName)) {
		throw new Error(`Refusing to generate a launcher for unsafe executable name: ${executableName}`);
	}
	const waylandTest = WAYLAND_SESSION_SIGNALS.map(renderSignalCondition).join(' || ');
	return [
		'#!/bin/sh',
		`# Generated by forge.config.ts from src/linux-session.ts for ${executableName}. Do not edit.`,
		'#',
		'# Chromium resolves its ozone platform before any application code runs, so the X11 or',
		'# Wayland decision has to be made here, in argv.',
		'#',
		`#   ${OZONE_OVERRIDE_ENV_VAR}=wayland  force native Wayland`,
		`#   ${OZONE_OVERRIDE_ENV_VAR}=x11      force X11 (XWayland inside a Wayland session)`,
		`#   ${OZONE_OVERRIDE_ENV_VAR}=auto     pass no switch and let Electron decide`,
		'',
		'DIR="$(dirname "$(readlink -f "$0")")"',
		`BIN="$DIR/${executableName}.bin"`,
		'',
		`case "$${OZONE_OVERRIDE_ENV_VAR}" in`,
		'  wayland|x11)',
		`    exec "$BIN" --ozone-platform="$${OZONE_OVERRIDE_ENV_VAR}" "$@"`,
		'    ;;',
		'  auto)',
		'    exec "$BIN" "$@"',
		'    ;;',
		'  ?*)',
		`    echo "${executableName}: ignoring ${OZONE_OVERRIDE_ENV_VAR}=$${OZONE_OVERRIDE_ENV_VAR}; expected wayland, x11 or auto" >&2`,
		'    ;;',
		'esac',
		'',
		`if ${waylandTest}; then`,
		'  exec "$BIN" --ozone-platform=wayland "$@"',
		'fi',
		'',
		'exec "$BIN" --ozone-platform=x11 "$@"',
		''
	].join('\n');
}
